name: wordshool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flip_card: ^0.7.0
  auto_size_text: ^3.0.0
  english_words: ^4.0.0
  # firebase_core: ^2.24.2
  google_generative_ai: ^0.4.5
  # cloud_firestore: ^4.14.0
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  just_audio: ^0.9.40
  dictionaryx: ^0.3.5
  # firebase_auth: ^4.16.0
  google_sign_in: ^7.1.0
  dio: ^5.7.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  go_router: ^16.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.3.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      path: packages/core/

flutter_gen:
  output: lib/core/assets/


flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/audio/
    - .env

