// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for production (`com.wordschool.mat`).
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbP47CHhfIwuFe6v3D7c1GQbljC9qTOM',
    appId: '1:87702505475:android:88daf17b6d2895a3d02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLXWtWySzMFB5Ya_sGJN_0f1cOgah5Ig',
    appId: '1:87702505475:web:acd1380a2f28a95fd02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    authDomain: 'wordschool-dev.firebaseapp.com',
    storageBucket: 'wordschool-dev.firebasestorage.app',
    measurementId: 'G-Q0QGW7W4RX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUeESiay4f92p2VfMZAmZnMHKV7kDK6A',
    appId: '1:87702505475:ios:9ffac947fb5fa204d02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
    androidClientId:
        '87702505475-hd86el48ffi4o4inms6p0ne61mh8s7b2.apps.googleusercontent.com',
    iosClientId:
        '87702505475-id78b5gh16rqa8eirni1jveo6orrkd81.apps.googleusercontent.com',
    iosBundleId: 'com.wordschool.mat',
  );
}
