// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for development (`com.wordschool.mat.dev`).
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DevFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbP47CHhfIwuFe6v3D7c1GQbljC9qTOM',
    appId: '1:87702505475:android:b1908ac159cb745dd02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUeESiay4f92p2VfMZAmZnMHKV7kDK6A',
    appId: '1:87702505475:ios:04ce67948906fa66d02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
    androidClientId: '87702505475-d76u6b420qtver76mc2u1tete9730oea.apps.googleusercontent.com',
    iosClientId: '87702505475-7mjteelebbalmv9r989ol3j6lbnvpagu.apps.googleusercontent.com',
    iosBundleId: 'com.wordschool.mat.dev',
  );
}
