// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbP47CHhfIwuFe6v3D7c1GQbljC9qTOM',
    appId: '1:87702505475:android:71ecbdaa65a9ae49d02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUeESiay4f92p2VfMZAmZnMHKV7kDK6A',
    appId: '1:87702505475:ios:1121678a38e1d161d02636',
    messagingSenderId: '87702505475',
    projectId: 'wordschool-dev',
    storageBucket: 'wordschool-dev.firebasestorage.app',
    androidClientId: '87702505475-hd86el48ffi4o4inms6p0ne61mh8s7b2.apps.googleusercontent.com',
    iosClientId: '87702505475-s42orbp34e2q414urk3ivdqha3iq4p87.apps.googleusercontent.com',
    iosBundleId: 'com.wordschoolgame.mat',
  );
}
